<a href="https://colab.research.google.com/github/tanvisonawane34/Machine-Learning/blob/main/Assignment-22/Assignment22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving heart.csv to heart.csv

In [ ]:
filepath = "/content/heart.csv"
data = pd.read_csv(filepath)

In [ ]:
data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [ ]:
# Seperate x and y
X = data.drop("HeartDisease", axis=1)
y = data["HeartDisease"]

In [ ]:
print(X)

     Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal
1     49   F           NAP        160          180          0     Normal
2     37   M           ATA        130          283          0         ST
3     48   F           ASY        138          214          0     Normal
4     54   M           NAP        150          195          0     Normal
..   ...  ..           ...        ...          ...        ...        ...
913   45   M            TA        110          264          0     Normal
914   68   M           ASY        144          193          1     Normal
915   57   M           ASY        130          131          0     Normal
916   57   F           ATA        130          236          0        LVH
917   38   M           NAP        138          175          0     Normal

     MaxHR ExerciseAngina  Oldpeak ST_Slope
0      172              N      0.0       Up
1      156              N      1.0     Flat
2       98              N      0.0       Up
3      108              Y      1.5     Flat
4      122              N      0.0       Up
..     ...            ...      ...      ...
913    132              N      1.2     Flat
914    141              N      3.4     Flat
915    115              Y      1.2     Flat
916    174              N      0.0     Flat
917    173              N      0.0       Up

[918 rows x 11 columns]

In [ ]:
print(y)

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [ ]:
# Encoding categorical columns
X = pd.get_dummies(X, drop_first=True)
X.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,True,False,True,False,True,False,False,False,True

In [ ]:
# Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (734, 15)
X_test shape: (184, 15)
y_train shape: (734,)
y_test shape: (184,)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
# predictions
y_pred = model.predict(X_test)

print("First 10 Actual Values:")
print(y_test.head(10).values)

print("First 10 Predicted Values:")
print(y_pred[:10])

First 10 Actual Values:
[0 1 1 1 0 1 1 0 1 1]
First 10 Predicted Values:
[0 0 1 1 0 1 1 0 1 1]

In [ ]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

TN, FP, FN, TP = cm.ravel()

print("TN:", TN)
print("FP:", FP)
print("FN:", FN)
print("TP:", TP)

Confusion Matrix:
[[67 10]
 [17 90]]
TN: 67
FP: 10
FN: 17
TP: 90

In [ ]:
# Model Evaluation
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83        77
           1       0.90      0.84      0.87       107

    accuracy                           0.85       184
   macro avg       0.85      0.86      0.85       184
weighted avg       0.86      0.85      0.85       184

In [ ]:
import joblib

joblib.dump(model, "heart_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")

print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!

In [ ]:
import joblib
import pandas as pd

# Load saved objects
loaded_model = joblib.load("heart_model.pkl")
loaded_scaler = joblib.load("scaler.pkl")
columns = joblib.load("columns.pkl")

# Create sample patient data
sample_data = pd.DataFrame([{
    "Age": 55,
    "Sex": "M",
    "ChestPainType": "ATA",
    "RestingBP": 140,
    "Cholesterol": 250,
    "FastingBS": 0,
    "RestingECG": "Normal",
    "MaxHR": 150,
    "ExerciseAngina": "N",
    "Oldpeak": 1.2,
    "ST_Slope": "Up"
}])

# Encode categorical columns
sample_data = pd.get_dummies(sample_data)

# Match the columns used during training
sample_data = sample_data.reindex(columns=columns, fill_value=0)

# Scale the sample data
sample_data_scaled = loaded_scaler.transform(sample_data)

# Make prediction
prediction = loaded_model.predict(sample_data_scaled)

print("Prediction:", prediction[0])

if prediction[0] == 1:
    print("Heart Disease: Yes")
else:
    print("Heart Disease: No")

Prediction: 0
Heart Disease: No

In [ ]:
from google.colab import files
files.download("heart_model.pkl")
files.download("scaler.pkl")
files.download("columns.pkl")