<a href="https://colab.research.google.com/github/tanvisonawane34/Machine-Learning/blob/main/Assignment-20/Assignment20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ford_car_dataset.csv to ford_car_dataset.csv

In [ ]:
filepath = "/content/ford_car_dataset.csv"
df = pd.read_csv(filepath)

In [ ]:
df.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [ ]:
# Separate Independent Features (X) and Dependent Feature (Y)
X = df.copy()
Y = df["price"]

In [ ]:
# Drop target column from X
X = X.drop("price", axis=1)

In [ ]:
# Print shape of X and Y
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

Shape of X: (17966, 8)
Shape of Y: (17966,)

In [ ]:
categorical_cols = X.select_dtypes(include="object").columns
categorical_cols

Index(['model', 'transmission', 'fuelType'], dtype='object')

In [ ]:
# Perform One-Hot Encoding
X_encoded = pd.get_dummies(X, columns=categorical_cols)

# Convert encoded data into integer type
X_encoded = X_encoded.astype(int)

# Display first 5 rows
X_encoded.head()

,year,mileage,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,...,model_ Transit Tourneo,model_Focus,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,15944,150,57,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,2018,9083,150,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,2017,12456,150,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,2019,10460,145,40,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,2019,1482,145,48,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [ ]:
from sklearn.preprocessing import StandardScaler
# Create StandardScaler object
scaler = StandardScaler()
numerical_cols = ["year", "mileage", "tax", "mpg", "engineSize"]

# Apply Standard Scaling
X_encoded[numerical_cols] = scaler.fit_transform(X_encoded[numerical_cols])
X_encoded.head()

,year,mileage,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,...,model_ Transit Tourneo,model_Focus,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,0.065128,-0.380998,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,0.552866,-0.733359,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,0.065128,-0.560132,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,1.040605,-0.662640,0.510727,-1.721198,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,1.040605,-1.123724,0.510727,-0.931045,-0.447984,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [ ]:
# Import train_test_split
from sklearn.model_selection import train_test_split

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    Y,
    test_size=0.33,
    random_state=42
)
# Print shapes
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (12037, 37)
Shape of X_test: (5929, 37)
Shape of y_train: (12037,)
Shape of y_test: (5929,)

In [ ]:
from sklearn.linear_model import LinearRegression

# Create Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)
print("Intercept:", model.intercept_)
print("Coefficients:")
print(model.coef_)

Intercept: 17008.928804463547
Coefficients:
[ 2.03726418e+03 -1.31955378e+03 -2.12184657e+01 -9.89026938e+02
  8.79613637e+02 -3.65234589e+03 -2.68053102e+03 -2.36339814e+03
  4.80150971e+03  1.02450948e+04 -2.72586392e+03 -6.34300645e+02
 -1.61638167e+02  2.03975409e+03 -2.41408106e+03  3.63649958e+02
 -4.09377412e+03 -6.56211930e+03 -4.23908486e+02 -1.23180996e+03
  9.37077816e+03  3.56715981e+03  5.34328137e-12  1.88351384e+03
 -1.81898940e-12 -2.25529492e+02  1.90037677e+03 -2.78174995e+03
 -4.22078695e+03  2.52157947e+02 -2.56550681e+02  4.39273388e+00
 -2.00100839e+03  0.00000000e+00  6.64511383e+03 -1.34334791e+03
 -3.30075753e+03]

In [ ]:
# Make predictions on the test data
y_pred = model.predict(X_test)

# Print first 10 predicted values
print("First 10 Predicted Values:")
print(y_pred[:10])

# Print first 10 actual values
print("\nFirst 10 Actual Values:")
print(y_test.head(10))

First 10 Predicted Values:
[ 6888.75487917  9328.62297666  9420.53085767  4495.6044587
  2429.68493278 16982.00675592 28491.10791141 12482.71267443
 11373.08042083 17275.68925414]

First 10 Actual Values:
17610     6995
7076      8999
1713      7998
1611      5491
16830     3790
14735    18200
322      22998
8164     11000
6822      7600
2133     14985
Name: price, dtype: int64

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.8401880779365886

In [ ]:
import joblib

joblib.dump(model, "LR_ford_car.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X_encoded.columns.tolist(), "columns.pkl")
print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!

In [ ]:
from google.colab import files
files.download("LR_ford_car.pkl")

In [ ]:
from google.colab import files
files.download("scaler.pkl")

In [ ]:
files.download("columns.pkl")